//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.28 at 02:09:42 PM CST 
//


package org.iata.oo.schema.AirShoppingRS;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServicePricingOnlyInd" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "servicePricingOnlyInd"
})
@XmlRootElement(name = "ServicePricingOnlyPreference")
public class ServicePricingOnlyPreference {

    @XmlElement(name = "ServicePricingOnlyInd")
    protected boolean servicePricingOnlyInd;

    /**
     * Gets the value of the servicePricingOnlyInd property.
     * 
     */
    public boolean isServicePricingOnlyInd() {
        return servicePricingOnlyInd;
    }

    /**
     * Sets the value of the servicePricingOnlyInd property.
     * 
     */
    public void setServicePricingOnlyInd(boolean value) {
        this.servicePricingOnlyInd = value;
    }

}
